name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Build Docker Image
        run: docker build -t gcr.io/$PROJECT_ID/my-app .

      - name: Run Tests
        run: |
          docker run --rm gcr.io/$PROJECT_ID/my-app pytest tests/
      
      - name: Security Scan
        uses: aquasecurity/trivy-action@v0.0.5
        with:
          image-ref: gcr.io/$PROJECT_ID/my-app

      - name: Push to Artifact Registry
        run: docker push gcr.io/$PROJECT_ID/my-app

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
