name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Build Docker Image
        run: docker build -t gcr.io/$PROJECT_ID/my-app .

      - name: Push to Artifact Registry
        run: docker push gcr.io/$PROJECT_ID/my-app
